config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'pages#home'

  resources :farms, only: [:new, :create, :edit, :update, :index, :show, :destroy,] do
    resource :bookings, only: [:new, :create]

    collection do
      get 'myfarms', to: "farms#myfarms"
    end
  end

  resources :bookings, only: [:edit, :update, :destroy] do

    resource :reviews, only: [:new, :create]

  end

   resources :reviews, only: [:edit, :update]

  get '/dashboard', to: "dashboard#index"
  get '/dashboard/owner', to: "dashboard#index_owner", as: :dashboard_owner

  patch '/dashboard/review/:id', to: "dashboard#review", as: :dashboard_review
  patch '/dashboard/approve/:id', to: "bookings#approve", as: :dashboard_approve
  patch '/dashboard/decline/:id', to: "bookings#decline", as: :dashboard_decline


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :farm
  has_one :review

  validate :end_date_after_start_date?


  def approve
    status = "Accepted"
  end

  def declined
    status = "Declined"
  end

  def review_ready?
    status == "Accepted" && end_date <= Time.now
  end

  def end_date_after_start_date?
    if end_date < start_date
      errors.add :end_date, "must be after start date"
    end
  end

end

app/models/farm.rb
class Farm < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user


  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true,  numericality: { greater_than_or_equal_to: 0 }
  validates :user, presence: true
  validates :photo, presence: true


  # Adds search functionality to the index page search bar
  include PgSearch
  pg_search_scope :search_by_farm_attributes,
  against: [ :name, :description, :city, :country, :address],
    using: {
      tsearch: { prefix: true } # <-- for eg now `london frm` will return something!
    }
  # pg_search_scope :user_associated_search,
  # against: [ :name, :description, :city, :country, :address],
  #   associated_against: {
  #     user: [ :email ]
  #   }


  def average_rating
    (self.reviews.pluck(:rating).reduce(:+) * 1.0 / self.reviews.count).floor
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :rating, inclusion: {in: [1,2,3,4,5]}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
  has_many :farms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exceptions
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new()

    @booking.start_date = Date.strptime(params[:booking][:start_date], "%Y-%m-%d")
    @booking.end_date  = Date.strptime(params[:booking][:end_date], "%Y-%m-%d")
    @farm = Farm.find(params[:farm_id])
    @user = current_user
    @booking.total_price = ((@booking.end_date - @booking.start_date).to_i) * @farm.price
    @booking.user = @user
    @booking.farm = @farm
    if @booking.save
      redirect_to dashboard_path
    else
      render 'farms/show', date_start: Date.new(1900,1,1)
    end

  end

  def edit
    @booking = Booking.find(params[:id])
    render :edit
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)

  end

  def approve
    @booking = Booking.find(params[:id])
    @booking.update(status: "Accepted")
    respond_to do |format|
        format.js  # <-- idem
      end
    end

    def decline
      @booking = Booking.find(params[:id])
      @booking.update(status: "Declined")
      respond_to do |format|
        format.js  # <-- idem
      end
    end

    def review
      @booking = Booking.find(params[:id])
    end

    private

    def booking_params
      params.require(:booking).permit(:start_date, :end_date)
    end
  end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @booking_guest = Booking.where(user: current_user).order(end_date: :desc)
    @booking_owner = Booking.joins(:farm).where(:farms => {:user => current_user})
  end

  def index_owner
    @booking_guest = Booking.where(user: current_user)
    @booking_owner = Booking.joins(:farm).where(:farms => {:user => current_user})
    @owner = true
    render :index
  end

  def review
    @booking = Booking.find(params[:id])
    respond_to do |format|
        format.js  # <-- idem
    end
  end

end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_farm, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @farms = Farm.search_by_farm_attributes(params[:query])
    else
      @farms = Farm.all
    end

    @form_title = "Farms"
    @form_myflat = false
    @farms = @farms.where.not(latitude: nil, longitude: nil)
    @markers = @farms.map do |farm|
      {
        lat: farm.latitude,
        lng: farm.longitude,
        infoWindow: { content: render_to_string(partial: "/farms/map_box", locals: { farm: farm }) }
      }
    end
  end

  def show
    @farm = Farm.find(params[:id])
    @booking = Booking.new
  end

  def myfarms
    @farms = Farm.where(user: current_user).where.not(latitude: nil, longitude: nil)
    @form_title = "My farms"
    @form_myflat = true

     @markers = @farms.map do |farm|
      {
        lat: farm.latitude,
        lng: farm.longitude,
        infoWindow: { content: render_to_string(partial: "/farms/map_box", locals: { farm: farm }) }
      }
    end
    render :index
  end

  def new
    @farm = Farm.new
    @user = current_user
  end

  def create
    @farm = Farm.new(farm_params)
    @farm.user = current_user
    if @farm.save
      redirect_to farms_path
    else
      render 'farms/new'
    end
  end

  private

  def farm_params
    params.require(:farm).permit(:name, :description, :address, :city, :country, :price, :photo)
  end

  def set_farm
    @farm = Farm.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @farms = Farm.all.first(10)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new()
  end

  def edit
    @review =  Review.find(params[:id])

  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking =  @booking
    if @review.save
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js
      end
    end
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
      <%= simple_form_for([@farm,@booking]) do |f| %>
      <%= f.input :start_date, as: :string, label: false, input_html: { class: 'datepicker' }, placeholder: "Check in"  %>
      <%= f.input :end_date, as: :string, label: false, input_html: { class: 'datepicker' }, placeholder: "Check out" %>
      <%= f.button :submit, 'Go to my farm !', class: "btn btn-primary" %>
        <% end %>

app/views/bookings/approve.js.erb
console.log("je suis la bro");
divStatus = document.getElementById('statusBooking<%=@booking.id%>')
divStatus.classList.remove('pending')
divStatus.classList.add('accepted')
divStatus.innerText = "Approved"

document.querySelectorAll(".booking-feedback<%=@booking.id%>").forEach((btn) => {
  console.log(btn)
  btn.classList.add('hidden');
});

app/views/bookings/decline.js.erb
divStatus = document.getElementById('statusBooking<%=@booking.id%>')
divStatus.classList.remove('pending')
divStatus.classList.add('declined')
divStatus.innerText = "Declined"

document.querySelectorAll(".booking-feedback<%=@booking.id%>").forEach((btn) => {
  console.log(btn)
  btn.classList.add('hidden');
});

app/views/dashboard/index.html.erb
<div class="tabs-container">
  <h2>Trips & Guests</h2>
  <div class="tabs">
    <a class="<%=  "tab #{@owner ? "" : "active"}"%>" id="tabx1" href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab">
      <h2>My Trips</h2>
    </a>
    <a class="<%=  "tab #{@owner ? "active" : ""}"%>" id="tabx2" href="#tab2" aria-controls="tab2" role="tab" data-toggle="tab">
      <h2>My Guests</h2>
    </a>
  </div>

  <div class="tab-content">
    <div role="tabpanel" class="<%=  "tab-pane #{@owner ? "" : "active"}"%>" id="tab1">
      <%= render 'dashboard/tabs/tab_guest' %>
    </div>
    <div role="tabpanel" class="<%=  "tab-pane #{@owner ? "active" : ""}"%>" id="tab2">
      <%= render 'dashboard/tabs/tab_owner' %>
    </div>
  </div>

</div>

app/views/dashboard/tabs/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
      <%= simple_form_for @booking,  as: :booking, url: booking_path(@booking), method: :patch do |f| %>
        <div class="modal-header">
         <button type="button" class="close btn-close" data-dismiss="modal" aria-hidden="true" id="btn-close">&times;</button>
         <h4 class="modal-title">Your trip's review</h4>
        </div>
        <div class="modal-body">
          <div class="form group">
            <%= f.input :rating, label: 'Your rating'%>
          </div>
          <div class="form-group">
            <%= f.input :review, label: 'Your review' %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.button :submit, "OK", class:"btn btn-primary btn-close"%>
        </div>
    <%end%>
  </div>
</div>

app/views/dashboard/tabs/_tab_guest.html.erb
<div class="bookings">
  <% @booking_guest.each do |booking| %>
  <div class="booking" id="booking<%= booking.id%>">
    <%= cl_image_tag(booking.farm.photo, class: "img-small") %>
    <div class="booking-body">
      <p><strong><%= "Booking from #{booking.start_date} to #{booking.end_date}"%></strong></p>
        <%= link_to "#{booking.farm.name} (#{booking.farm.address}, #{booking.farm.country}) ", farm_path(booking.farm), style:"color:gray;"  %>
    </div>
    <div class="booking-status">
      <%status_erb = booking.status%>
      <p class="<%= "status #{status_erb.downcase}" %>"><%= status_erb %></p>
      <p class="price"><%= booking.total_price %> USD</p>
    </div>
    <div class="booking-review text-center">
      <% if booking.review_ready? %>
        <p class="review-rating" id="rating-booking<%= booking.id%>" >
          <% if !booking.review.nil? %>
            <% booking.review.rating.times do %>
              <i class="far fa-star"></i>
            <% end %>
          <% end %>
        </p>
        <div class="review-rating" id="rating-buttons<%= booking.id%>">
          <% if booking.review.nil? %>
            <%= link_to "Add a review", new_booking_reviews_path(booking_id: booking.id), remote: true, class: "btn btn-primary btn-sm"  %>
          <% else %>
            <%= link_to "Edit", edit_review_path(booking.review.id), remote: true, class: "btn btn-primary btn-sm"  %>
          <% end %>
        </div>

      <% end %>
    </div>
  </div>
  <% end %>
</div>


<!-- Modal HTML -->
<div id="myModal" class="modal fade " tabindex="-1">

</div>

app/views/dashboard/tabs/_tab_owner.html.erb
<div class="bookings">
  <% @booking_owner.each do |booking| %>

  <div class="booking" id=<%= "booking#{booking.id}"%>>
    <div class="booking-name">
      <h3><%=  booking.user.email%></h3>
    </div>
    <div class="booking-body">
      <p><strong><%= "Booking from #{booking.start_date} to #{booking.end_date}"%></strong></p>
      <p><%= "#{booking.farm.name} (#{booking.farm.address}, #{booking.farm.country}) " %></p>
    </div>

    <div class="booking-status">
     <%status_erb = booking.status%>

     <p id= <%= "statusBooking#{booking.id}"%> class="<%= "status #{status_erb.downcase}" %>"><%= status_erb %></p>

     <p class="price"><%= booking.total_price %> USD</p>
   </div>
   <div class="booking-feedback<%=booking.id%> <%= booking.status == "Pending" ? "" : "hidden"  %>">
     <%= link_to "Approved", dashboard_approve_path(booking.id), method: :patch, remote: true, class: "btn btn-primary btn-feedback btn-sm" %>
     <%= link_to "Declined", dashboard_decline_path(booking.id), method: :patch, remote: true, class: "btn btn-danger btn-feedback btn-sm" %>
   </div>
 </div>

 <% end %>

</div>

app/views/farms/_form.html.erb
<div class="urb-form-container">
  <%= simple_form_for(@farm) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :country, :as => :string%>
    <%= f.input :city %>
    <%= f.input :price %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-primary" %>
  </div>
  <% end %>
</div>

app/views/farms/_map_box.html.erb
<div><%= farm.address %></div>
<%= link_to farm.name, farm_path(farm) %>

app/views/farms/index.html.erb
<!-- <div class="container"> -->

<div class="urb-title-area-container-with-button">
<h2><%= @form_title %></h2>
<%= button_to "Add a new farm", new_farm_path, method: :get, class: @form_myflat ? "btn btn-primary" : "hidden" %>
</div>

<div class="urb-form-container" <%= @form_myflat ? "hidden" : "visible" %>>
  <%= form_tag farms_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a Farm!"
    %>
  <% end %>
</div>
  <div class="main-container">
    <%= render 'shared/cards', class: "cards" %>
      <div
        id="map"
        style="width: 100%, border-radius: 15px;
        margin-top: 14px;
        margin-right: 30px;
        height: 600px;"

        data-markers="<%= @markers.to_json %>"
      >
    </div>
  </div>

app/views/farms/new.html.erb
<%= render 'form', farm: @farm %>

app/views/farms/show.html.erb
<%= render 'components/show-banner'%>

<div class="container">
  <div class="grid">
    <div class="grid-title">
     <h4><strong><%= @farm.name %></strong></h4>
     <p> <%= @farm.address %> <%= @farm.country %></p>
   </div>

   <div class="grid-data">

    <p>Average rating :

      <% if @farm.reviews.count != 0 %>
      <% @farm.average_rating.times do %>
      <i class="far fa-star"></i>
      <% end %>
      <% else %>
      no rating yet
      <% end %>
    </p>
    <p>Price per night : <%= @farm.price %> USD</p>
    <p>Owner : <%= @farm.user.email %></p>
  </div>



  <div class="grid-description">
    <div class="grid-header">
      <h3> Description </h3>

    </div>

    <p><%= @farm.description %></p>
  </div>


  <div class="grid-review">
    <div class="grid-header">
      <h3> Reviews <%= "(#{@farm.reviews.count})" unless @farm.reviews.nil? %></h3>
    </div>

    <div class="grid-reviews" >

      <% if !@farm.reviews.nil? %>

      <% @farm.reviews.each do |review| %>
      <div class="review">
        <div class="review-header">
          <div>
          <%= review.booking.user.email %></div>
          <div>
          <% review.rating.times do %>
            <i class="far fa-star"></i>
          <% end %>
          </div>
        </div>
        <div class="review-text">
         <%= review.description %>
       </div>
     </div>
     <%end%>
     <%end%>
   </div>
 </div>

 <div class="grid-form">
  <div class="grid-header">
    <h3> Book now ! </h3>
  </div>
  <%= render 'bookings/form' %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Farm-Vacation</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <%= render 'components/home-banner'%>
<div>
<div class="urb-title-area-container">
  <h2>Top Ten Farms</h2>
</div>
<div class="urb-main-area-container-with-cards">
  <%= render 'shared/cards' %>
<div>

<!-- <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> -->

app/views/reviews/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
      <%= simple_form_for [@booking, @review], remote: true do |f| %>
        <div class="modal-header">
         <button type="button" class="close btn-close" data-dismiss="modal" aria-hidden="true" id="btn-close">&times;</button>
         <h4 class="modal-title">Your trip's review</h4>
        </div>
        <div class="modal-body">
          <div class="form group">
            <%= f.input :rating, label: 'Your rating'%>
          </div>
          <div class="form-group">
            <%= f.input :description, label: 'Your review' %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.button :submit, "OK", remote: true, class:"btn btn-primary btn-close"%>
        </div>
    <%end%>
  </div>
</div>

app/views/reviews/_review.html.erb
<% review.name %>

app/views/reviews/create.js.erb
// SHOW MODAL
$('#myModal').modal('show');

// FUNCTION TO MODIFY DOM
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('myModal');
  newReviewForm.innerHTML = innerHTML;
}

// CHECK IF THE REVIEW IS IN ERROR (Y : RENDER THE FORM + ERROR, N : UPDATE THE DOM)
<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", booking: @booking, review: @review %>');
<% else %>
  innerHTML = ""
  <% @review.rating.times do %>
    innerHTML += "<i class='far fa-star'></i>"
  <% end %>
  document.getElementById("rating-booking<%= @review.booking.id %>").innerHTML = innerHTML
  document.getElementById("rating-buttons<%= @review.booking.id %>").innerHTML = '<%= link_to "Edit", edit_review_path(@booking.review.id), remote: true, class: "btn btn-primary btn-sm"  %>'
  $('#myModal').modal('hide');
  $('.modal-backdrop').remove();
<% end %>

// ADD EVENT LISTENER ON BUTTONS TO CLOSE THE MODAL
document.querySelectorAll(".btn-close").forEach((btn) => {
  btn.addEventListener("click", (event) => {
   $('#myModal').modal('hide');
   $('.modal-backdrop fade in').remove()
 });
});

app/views/reviews/edit.html.erb
<%= render 'form', reviews: @review%>

app/views/reviews/edit.js.erb
// SHOW MODAL
$('#myModal').modal('show');

// FUNCTION TO MODIFY DOM
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('myModal');
  newReviewForm.innerHTML = innerHTML;
}

// CALL OF THE FUNCTION
refreshForm('<%= j render "reviews/form", booking: @booking, review: @review %>');


// ADD EVENT LISTENER ON BUTTONS TO CLOSE THE MODAL
document.querySelectorAll(".btn-close").forEach((btn) => {
  btn.addEventListener("click", (event) => {
   $('#myModal').modal('hide');
   $('.modal-backdrop fade in').remove()
 });
});

app/views/reviews/new.html.erb
<%= render 'form', review: @review %>

app/views/reviews/new.js.erb
// SHOW MODAL
$('#myModal').modal('show');

// FUNCTION TO MODIFY DOM
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('myModal');
  newReviewForm.innerHTML = innerHTML;
}

// CALL OF THE FUNCTION
refreshForm('<%= j render "reviews/form", booking: @booking, review: @review %>');

// ADD EVENT LISTENER ON BUTTONS TO CLOSE THE MODAL
document.querySelectorAll(".btn-close").forEach((btn) => {
  btn.addEventListener("click", (event) => {
   $('#myModal').modal('hide');
   $('.modal-backdrop').remove()
 });
});

app/views/reviews/update.js.erb
$('#myModal').modal('show');

function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('myModal');
  newReviewForm.innerHTML = innerHTML;
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", booking: @booking, review:  @review %>');
<% else %>
  innerHTML = ""
  <% @review.rating.times do %>
    innerHTML += "<i class='far fa-star'></i>"
  <% end %>
    document.getElementById("rating-booking<%= @review.booking.id %>").innerHTML = innerHTML
    $('#myModal').modal('hide');
    $('.modal-backdrop').remove()
<% end %>

// ADD EVENT LISTENER ON BUTTONS TO CLOSE THE MODAL
document.querySelectorAll(".btn-close").forEach((btn) => {
  btn.addEventListener("click", (event) => {
   $('#myModal').modal('hide');
   $('.modal-backdrop').remove()
 });
});

app/views/shared/_cards.html.erb
 <div class="cards-container">
   <div class="row">

    <%  @farms.each do |farm| %>
     <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path ("10.png")%>);">
         <div class="card-category"><%= farm.description %>
         </div>
          <div class="card-description">
          <h2><%=farm.name%></h2>
          <p>$<%=farm.price%>per night</p>
          <% if farm.reviews.count != 0 %>
          <% farm.average_rating.times do %>
          <i class="far fa-star"></i>
          <% end %>
          <% else %>
          <%= "" %>
      <% end %>
          </div>
          <a class="card-link" href="#" ></a>
          <%= link_to "", farm_path(farm), :class=> "card-link" %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "greenhouse.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <!-- Links when logged in -->
    <%= link_to "Search", farms_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Trips & Guests", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "My Farms", myfarms_farms_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "pig.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <!-- Login link (when logged out) -->

    <%= link_to "Search", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">

    <% if user_signed_in? %>
    <!-- Links when logged in -->

    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <li><%= link_to "Search", farms_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li><%= link_to "Trips & Guests", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li><%= link_to "My Farms", myfarms_farms_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li>
          <%= link_to "#" do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
          <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>
<% else %>
<!-- Login link (when logged out) -->
<div class="dropdown">
  <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
  <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
    <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
    <li><%= link_to "Search", "#", class: "navbar-wagon-item navbar-wagon-link" %></li>
  </ul>
</div>
</div>
</div>
<% end %>